### ISSUE TITLE
Can wit-cms export to gh-pages?

### ISSUE THREAD

**Issue by z3cka** [chrisallenlane/wit-cms#5]
I'm wondering if wit-cms can generate static HTML, etc. to be hosted via gitHub page.

Thanks.

**Comment by chrisallenlane** [comment]
Sorry - I wasn't "watching" my own repo apparently, and never saw this ticket! D:

If you still care about this:

`wit` doesn't have any specific mechanism that allows for that, however, IIRC, github pages is powered by Jekyll, and Jekyll likewise just sources markdown files for content. With that said, you can probably mostly copy your markdown files from your wit site to a jekyll site, and mostly be good-to-go.

**Comment by z3cka** [comment]
No worries– thanks for the reply! I was thinking more along the lines of a generator. I found another project that does exactly what I was looking for: https://hexo.io/

Cheers.
